### ISSUE TITLE
Error While Installing

### ISSUE THREAD

**Issue by theutz** [pixelfear/laravel-view-debug#4]
After running `composer require pixelfear/laravel-view-debug`, I get the following error:

```
 Error 

  Call to undefined method Pixelfear\ViewDebug\DebugEngine::forgetCompiledOrNotExpired()

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ViewClearCommand.php:75
     71▕         }
     72▕ 
     73▕         $this->laravel['view.engine.resolver']
     74▕             ->resolve('blade')
  ➜  75▕             ->forgetCompiledOrNotExpired();
     76▕ 
     77▕         foreach ($this->files->glob("{$path}/*") as $view) {
     78▕             $this->files->delete($view);
     79▕         }

      +25 vendor frames 
  26  artisan:35
```

Everything else seems to work fine, though. Just thought I'd report it in case it's an easy fix!

**Comment by jasonvarga** [comment]
Sorry for the delay. I don't see this error. Let me know what version of Laravel you're using. But maybe it's sorted itself out.

**Comment by theutz** [comment]
I can't reproduce it on any of my regular projects anymore, so it must've been just a transient thing. Thanks for the response!
