### ISSUE TITLE
Call to undefined method forgetCompiledOrNotExpired()

### ISSUE THREAD

**Issue by jaygeorge** [pixelfear/laravel-view-debug#7]
Hey, I just tried to install on a Statamic v4.20.0 project and I get this error message:

```
Call to undefined method Pixelfear\ViewDebug\DebugEngine::forgetCompiledOrNotExpired()

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ViewClearCommand.php:75
     71▕         }
     72▕ 
     73▕         $this->laravel['view.engine.resolver']
     74▕             ->resolve('blade')
  ➜  75▕             ->forgetCompiledOrNotExpired();
     76▕ 
     77▕         foreach ($this->files->glob("{$path}/*") as $view) {
     78▕             $this->files->delete($view);
     79▕         }

      +25 vendor frames 
  26  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan statamic:install --ansi handling the post-autoload-dump event returned with error code 1
```

Thanks in advance

**Comment by jasonvarga** [comment]
Okay so this is #4 again which I couldn't reproduce, but now it seems obvious. It happens during the `view:clear` command.

**Comment by jaygeorge** [comment]
Ohhh, sorry for the duplication. FWIW it seems to have been installed and it's working, despite the error.

**Comment by jasonvarga** [comment]
Yeah it'll work, but `view:clear` won't.

**Comment by jaygeorge** [comment]
Could I buy you a couple of Irish coffees to fix this? 😬

**Comment by jasonvarga** [comment]
Crap I'm sorry 😊 I had already fixed it but never merged or released. Done now! https://github.com/pixelfear/laravel-view-debug/releases/tag/v2.1.0

On the house.

**Comment by jaygeorge** [comment]
Got you a couple of Irish coffees anyway. This is a very useful addon at times. See you in a couple of months, mate!
